### ISSUE TITLE
Make title a clickable link to go to homepage

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#104]
## Desciption
Make the CommunityFocus logo text at the top left of the page go to the '/' homepage.

## How
1. Use `react-router-dom` package to make the text into a clickable text (no styling changes)
2. It should route to `/` page
3. Do the same for all 3 pages (LandingPage, Room, DefaultRoom)

## Screenshot
<img width="1069" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/c7f0e8ad-6e81-4d59-af1d-e99f5026c80f">

**Comment by mjbramich** [comment]
I can take this on if needed (:

**Comment by nmpereira** [comment]
> I can take this on if needed (:

Assigned it to you. Let me know if you need any help!
