### ISSUE TITLE
The header and footer components dont stick to the top/bottom when scrolling

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#105]
## Description
The header component doesn't stick to the top when down scrolling very hard. It leaves a gap at the top. The Footer component also does the same thing

## Screenshots

<img width="1512" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/c74fa3be-8fb1-419b-a0c9-ccf062d962dd">

**Comment by MICHAEL-STEWART0** [comment]
I can do this!
