### ISSUE TITLE
Timer Text Display Issue: Inability to Change Timer Text Automatically  for break and for work session  - Requires Page Reload

### ISSUE THREAD

**Issue by shubhamsinghbundela** [CommunityFocus/CommunityFocus#107]
**Describe the bug**

Upon completion of any session, whether it be a break or a work session, users are presented with the option to select the duration for the subsequent work or break period. However, after users make their selection and the work timer commences, the corresponding text for the work session fails to update automatically. This issue also applies to break sessions, requiring users to reload the page for the correct display. We aim to make this update happen automatically.

**To Reproduce**

1. Visit https://communityfocus.app/early-birds
2. Select any timer for a specific session.
3. After the session completes, when you select the timer again, you'll notice that the corresponding text for that particular session does not update as expected.

**Expected behavior**

After completing a session and selecting the timer again, the expected behavior is for the corresponding text to automatically update, accurately reflecting the current session's details without the need for manual intervention.

**Screenshots**

https://github.com/CommunityFocus/CommunityFocus/assets/107163260/5de107ee-09e1-4af1-9941-d61afb0887a4

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: chrome
 - Version: 120.0.6099.71 (Official Build) (64-bit)

**Comment by nmpereira** [comment]
fixed via https://github.com/CommunityFocus/cf-backend/pull/74
