### ISSUE TITLE
Update the connection status/state on the frontend

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#11]
## What
~~The code that says state: true /false needs to be removed, along with any related unnecessary code~~

Instead of removing the state, we can rename it to 'Connected: ![image 1](https://github.com/CommunityFocus/CommunityFocus/assets/45009203/711eb4a3-4d35-4d90-a0bf-75b169acb143)' or  'Lost connection: ![image 2](https://github.com/CommunityFocus/CommunityFocus/assets/45009203/bcac5be6-9ca9-4d3b-9cba-5a30a91b02f5)'

<img width="224" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/d0029b20-a597-4d5d-ac1a-37e21ae04fb9">

<img width="202" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/eb81396d-b760-46e9-8c87-dc93356f024d">

Figma File: https://www.figma.com/file/QBlosE3N87ufFSx3hEPJ69/CommunityFocus?type=design&node-id=302-608&t=cED6JHpNYGyGceLI-0

**Comment by eyejabb** [comment]
I got dis one. 👍
