### ISSUE TITLE
Discussion for which CSS framework to use

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#2]
## Vote for the following

TailwindCSS - 🎉 
React Styled components - 🚀

**Comment by nmpereira** [comment]
In my opinion, TailwindCss gets really messy because of the classNames, unless we use a package like DaisyUI or flowbite, which makes it so that you don't have to use a ton of classNames. However, using packages like DaisyUI or flowbite makes the components very opinionated, and customizing them to our design will be harder.

I'm in favor of styled components because of the pros @riddlew mentioned above.

**Comment by RamadanCRaji** [comment]
I am more experienced with CSS style but i am willing to learn tailwind

**Comment by HondaChan14** [comment]
> 

youll enjoy how easy it is to pick so dont worry :) especially the documentation
