### ISSUE TITLE
Extend the destroyTimer to more than 10 seconds

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#25]
## Description
When a timer is created, the timerStore object on the server stores the roomName, timer instance (setTimeout), list of connected users, and the `destroyTimer` instance (setTimeout).

The destroyTimer acts as a way to purge the roomName and all its related properties when no one is using a timer. For example, when a user creates and uses room `/test123`, and leaves it after using it, the timer instance will continue to tick down, until the destroyTimer deletes the roomName. This is done so that memory, computing power etc dont get added up by ununsed timers.

Currently, the destroyTimer count is set to 10 seconds. We can update this value to 2 mins, to allow users to join if disconnected unintentionally.

**Comment by KhuloodHassan** [comment]
I'll take this
