### ISSUE TITLE
Frontend missing GitHub issue templates

### ISSUE THREAD

**Issue by riddlew** [CommunityFocus/CommunityFocus#29]
Backend currently contains two issue templates:
* bug_report.md
* feature_request.md

Should we also include these templates (or similar ones) in the frontend as well?

**Comment by nmpereira** [comment]
Also add a PR template for both frontend and backend

**Comment by nmpereira** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
