### ISSUE TITLE
Add brand icon

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#30]
## Description
1. Look for icon options 
2. Discuss with team/get a vote going
3. Add icon to app

**Comment by XakHD** [comment]
ill work on this

**Comment by riddlew** [comment]
![cf_favicon](https://github.com/CommunityFocus/CommunityFocus/assets/6940264/9e75a1b6-62e4-43ba-a28a-054babef3e50)

Here's a favicon we could use until we come up with something better.
