### ISSUE TITLE
Add functionality for users to add their names to the timer

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#32]
## Description
Add functionality for a user to add their name on to the timer. This will be reflected on the top right as "Hi, Mario!" and also on the update logs like "Mario changed the timer", "Mario Paused the timer" etc.

This also includes the user input like the modal, adding and reading the name from local storage.

This issue will not involve anything on the backend. This will be purely frontend. There will be another ticket for backend functionality.

## Discussion
- Do we use a modal to change the name?
- Do we suggest a randomized name for the user?

**Comment by nmpereira** [comment]
previous implementaion: https://vulture.nmpereira.com/humpty%20dumpty

![image](https://github.com/CommunityFocus/CommunityFocus/assets/45009203/042dd2b9-0b55-497a-bfe9-b208c7a42873)

**Comment by IntelliJinceTech** [comment]
Additional details from Discord:

- Assuming a new user, a name window should appear once they Join a room. They would be asked to input their name themselves or choose from offered. (Choosing from offered is out of scope for this ticket)
- If the user exists aka if the username exists from the browser's local storage:
    - don't bring up the name window
- Once in the room, present users the option to change their username on a name change modal and update their local storage with the updated username on submission.
