### ISSUE TITLE
React component testing

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#34]

**Comment by alcpereira** [comment]
I recommend [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/).
Also add this [eslint plugin](https://testing-library.com/docs/ecosystem-eslint-plugin-testing-library/).

I can do code review if needed.

Maybe split this Issues into 3+:
- Implement React Testing Library and eslint plugin (basically only updating `package.json`, `package-lock.json` and `eslintrc.cjs`
- Implement CI pipeline (advanced)
- Add test for component X (maybe start with a simple one)
