### ISSUE TITLE
Timer ticks down past 0 into negative values

### ISSUE THREAD

**Issue by riddlew** [CommunityFocus/CommunityFocus#41]
The frontend code has a major bug that causes timers to continue past 0 and count down into negative values.

![badtimer](https://github.com/CommunityFocus/CommunityFocus/assets/6940264/98240749-4a07-4724-849d-b7762dbfb5c0)

**Comment by nmpereira** [comment]
One of the values that triggered it was `3e123`. We need to investigate why it happens.

**Comment by riddlew** [comment]
> One of the values that triggered it was `3e123`. We need to investigate why it happens.

3e123 gets casted as a number and ends up as just 3. This works if you replace 3e with any other value such as 1234e123, which would be 1234 seconds. The number input seems to count any value ending in e with 1-3 digits at the end (1e1, 1e12, and 1e123 are all valid), although those parts just drop off of the value (123e123 is just 123 (e123 dropped)).

We *could* do client-side validation to prevent this, but I don't think it's a major issue as long as we're validating server-side values to prevent someone from sending a non-number and breaking the server. The major issue is the timer counting down past 0, which occurs even with normal numbers such as 5 seconds.
