### ISSUE TITLE
Create header component

### ISSUE THREAD

**Issue by riddlew** [CommunityFocus/CommunityFocus#45]
## What
This will be the header component that will contain the Logo (#44) and WelcomeMessage (#43) components along the top of the page. This issue depends on those two issues being finished, so this cannot be done until those issues are complete.

Please reference the Figma design at https://www.figma.com/file/aOxY6JeMesN7fq72tZsbD9/Untitled?type=design&t=ojy9KXiE1A3V8cHZ-0 for an idea of how this component will look (design subject to change). This component is located at the top of the screen.

![Header](https://github.com/CommunityFocus/CommunityFocus/assets/6940264/04f8325e-0353-4370-a734-fd395ecf059c)

## Details
- Component that creates a header containing the Logo and WelcomeMessage components.
  - Example:
    ```javascript
    <Header />

    // result
    <div>
        <Logo />
        <WelcomeMessage />
    </div>
    ```
- No styling required as of right now, only the basic functionality.
- No testing required as of right now, this will be handled in a separate issue.

**Comment by HarmanRo** [comment]
ill take this
