### ISSUE TITLE
Create footer component

### ISSUE THREAD

**Issue by riddlew** [CommunityFocus/CommunityFocus#47]
## What
This will be the footer component that will contain the MembersUsingMessage component (#46). This issue depends on the MembersUsingMessage comopnent being completed first, so this cannot be done until that issue is complete.

Please reference the Figma design at https://www.figma.com/file/aOxY6JeMesN7fq72tZsbD9/Untitled?type=design&t=ojy9KXiE1A3V8cHZ-0 for an idea of how this component will look (design subject to change). This component is located at the bottom of the screen.

![Footer](https://github.com/CommunityFocus/CommunityFocus/assets/6940264/5ecf951c-3716-41f6-9f42-7b049e18c8fa)

## Details
- Component that creates a footer containing the MembersUsingMessage component.
  - Example:
    ```javascript
    <Footer/>

    // result
    <footer>
        <MembersUsingMessage />
    </footer>
    ```
- No styling required as of right now, only the basic functionality.
- No testing required as of right now, this will be handled in a separate issue.

**Comment by Natashka333** [comment]
@nmpereira I can take this issue

**Comment by nmpereira** [comment]
To clarify, this issue is to create a footer component that needs to be styled to stick to the bottom of the page.

The footer will show on the home page '/' and on '/:room' page
