### ISSUE TITLE
[BUG]- Port number in frontend README and vite.config.ts is incorrect

### ISSUE THREAD

**Issue by eyejabb** [CommunityFocus/CommunityFocus#60]
**Describe the bug**
The established PORT number in "vite.config.ts" is correct, but the corresponding PORT numbers in the README and line 17 of "vite.config.ts" show an incorrect port number, and am unable to connect to the MVP using the provided documentation.

**To Reproduce**
1. Attempt to follow initial instructions in cloning the repos and getting "npm run dev" working.

**Expected behavior**
Does not connect to app due to incorrect PORT nunber.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 113.0.5672.126 (Official Build) (x86_64)

**Comment by KhuloodHassan** [comment]
The README files show `5173` but the contributing documentation shows `5100` which is the correct port! The READMEs need to be updated to reflect the correct port.

**Comment by nmpereira** [comment]
@eyejabb Can you please also update the port numbers on all the other repo readmes as well please?
