### ISSUE TITLE
Style timer minute buttons to circles with size based on value

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#62]
## Description
Style the timer minute buttons (5,10,15...60) to circles. The diameter of the circle needs to be a function of the value (not 1:1, but a percentage).

Centering/moving the buttons to the center will be done in a separate issue

Requirements:  
1. They should be white circles, with a shadow added to it
2. The size should be based on the value, but not a direct relationship. For example, 5 mins should not be half the size of 10 mins, but should only be slightly smaller.
3. Test with values upto 120. The size should NOT be abnormally large.
4. No need to move the buttons to the center of the page (will be done in another issue)

Before:
<img width="891" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/9e64bd8d-eb2e-4b17-9d61-1f688a663dbc">

After
<img width="860" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/e51a9f0f-64c0-47d4-b574-8704acc7f41c">

Figma: https://www.figma.com/file/QBlosE3N87ufFSx3hEPJ69/CommunityFocus?type=design&node-id=0-1&t=cED6JHpNYGyGceLI-0

**Comment by KhuloodHassan** [comment]
If this is open and ready to work on, I'll take it!

**Comment by nmpereira** [comment]
> If this is open and ready to work on, I'll take it!

It's ready to work on. Assigned it!
