### ISSUE TITLE
Style the pause button

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#63]
## Description
Style the Pause button to the following specs

Before:
<img width="104" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/c3555cc6-699b-4cb0-b778-768d4c556c02">

After:
<img width="105" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/8c77819d-a88f-455a-bce5-49341b5f0b32">

"Resume" icon:
<img width="126" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/18ef54c4-9f2a-4e73-a49b-9e9d13af7126">

Full page for reference:

<img width="1029" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/4e4daa98-5dea-48fc-90ff-bc4fe7273519">

Figma: https://www.figma.com/file/QBlosE3N87ufFSx3hEPJ69/CommunityFocus?type=design&node-id=0-1&t=cED6JHpNYGyGceLI-0

**Comment by Natashka333** [comment]
Caleb and I can take it

**Comment by Caleb-Cohen** [comment]
I'll take this on with @natashka333

**Comment by Natashka333** [comment]
Question: This says styled. Should it be it's own react component? or just some button with conditional rendering on the page?

**Comment by nmpereira** [comment]
> Question: This says styled. Should it be it's own react component? or just some button with conditional rendering on the page?

Suggestion #1: The control buttons (pause, reset, stop, share) can be the same component, with different icons in the middle and a different onclick function

Suggestion #2: They can all be different components completely separate of each other. 

I suggest doing #2 since 3-4 different people are assigned the task and since we are doing this for the purpose of learning. We can have an issue later to refactor and make it a single component like in #1


Thoughts?

**Comment by Caleb-Cohen** [comment]
Haven't forgotten about this. Just had other issues take priority. I'm expected to update the PR to feedback by Wednesday.
