### ISSUE TITLE
Style the Reset button

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#64]
## Description
Style the Reset button to the following specs

Before:
<img width="93" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/c1a8795a-93bd-4d3d-aef7-837c66257f65">

After:
<img width="102" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/ffd80aea-9a7c-4921-8e8f-beb51a316d3f">

Full page for reference:

<img width="1029" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/4e4daa98-5dea-48fc-90ff-bc4fe7273519">

Figma: https://www.figma.com/file/QBlosE3N87ufFSx3hEPJ69/CommunityFocus?type=design&node-id=0-1&t=cED6JHpNYGyGceLI-0

**Comment by AhmedHHamdy** [comment]
I'll take this one
