### ISSUE TITLE
Style the Share button

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#65]
## Description
Style the Share button to the following specs

Before:
<img width="116" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/294af113-7a6b-41be-beae-0142b7a83a32">

After:
<img width="95" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/20c121fe-0928-4b7a-a557-7ca47d3b25bc">

Full page for reference:

<img width="1029" alt="image" src="https://github.com/CommunityFocus/CommunityFocus/assets/45009203/4e4daa98-5dea-48fc-90ff-bc4fe7273519">

Figma: https://www.figma.com/file/QBlosE3N87ufFSx3hEPJ69/CommunityFocus?type=design&node-id=0-1&t=cED6JHpNYGyGceLI-0

**Comment by itSnZayn** [comment]
i will take this one
