### ISSUE TITLE
List of Suggested Random User Names on Joining Room (New User)

### ISSUE THREAD

**Issue by IntelliJinceTech** [CommunityFocus/CommunityFocus#66]
**Is your feature request related to a problem? Please describe.**
When a new user (defined as a user that does not have a username set in their local storage) joins a room, they should have either the option to enter their own selected username OR to select from a suggestion list of random generated strings (e.g. `dynamic dog` or similar). 

**Describe the solution you'd like**
Give a new user the option on joining the room to select from a list of predefined or pre-generated string combinations to adopt as their username within the room. 

**Describe alternatives you've considered**
In relation to #32 - this would give users an alternative way to select their name.

**Comment by nmpereira** [comment]
Is there a good case for offering random usernames like the above?

I was thinking if the user is forced to enter a name, they are more likely to add a name that is identifiable to them.

Giving random username suggestions will discourage personalized names, therefore making it harder for other users to identify them. 

They are still totally free to add whatever name they would like (even "dynamic dog"), but we want to encourage personalized usernames
