### ISSUE TITLE
Add background color to LandingPage and DefaultRoom components

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#69]
## Description
Add a background color (radial-gradient) to the LandingPage. See the Figma file for design specs and CSS.

Add the same background to both LandingPage and DefaultRoom components.

Note: the green background is a very subtle radial gradient and not a solid color.

## Design spec
![image](https://github.com/CommunityFocus/CommunityFocus/assets/45009203/b38db0b2-3342-43b8-afb2-07689ba962ee)

## Figma file
https://www.figma.com/file/QBlosE3N87ufFSx3hEPJ69/CommunityFocus?type=design&node-id=215-136&t=nJWI1TbXYOuY3TJQ-4

**Comment by mayankjain25** [comment]
I can do this. Can you please assign it to me?

**Comment by nmpereira** [comment]
> I can do this. Can you please assign it to me?

@mayankjain25 Thank you for volunteering! I assigned the issue to you. If you need any help, please reach out to me here, or discord (discord username: mariojuanaaa)

If you haven't already, please go through the docs for the get started documentation https://github.com/CommunityFocus/CommunityFocus
