### ISSUE TITLE
Add documentation on how to contribute

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#7]

**Comment by intelagense** [comment]
We could probably add details on how to reference or close issues in the org when making a PR since all the issues are located in this repo.
i.e. `closes CommunityFocus
/
CommunityFocus#1234`

**Comment by KhuloodHassan** [comment]
Can I work on this? There are members contributing who have very minimal experience with github and need step by step guide from forking to installing dependencies. I could whip something up real quick.

**Comment by nmpereira** [comment]
@KhuloodHassan Thank you for volunteering for it. Yes please go ahead and add some contributing documentation.

This will also likely be an ongoing task rather than a once-n-done.
