### ISSUE TITLE
Create frontend button to emit a 'breakTimer' socket message to server

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#80]
## Description
Create a button to switch from the work timer to the break timer.

Note: No need to add styling to the button, that will be a different issue.

## How
1. Create a button with the title 'Have a break'
2. The onClick would emit a socket message with the event name 'breakTimer', along with the roomName, user's username (from local storage. See https://github.com/CommunityFocus/CommunityFocus/issues/32)
3. On the server, listen to the socket message with event name 'breakTimer', and console log it, along with the roomName, username

Additional info:
If you want to see a similar functionality, you can see the timer button (5 min, 10 min buttons) or the pause/reset button.

## Dependencies
None

## Screenshot
![image](https://github.com/CommunityFocus/CommunityFocus/assets/45009203/332f5bc6-a51b-48c9-98e7-c52dfc323f5c)

**Comment by nmpereira** [comment]
> Can I take this?

Assigned it to you! Thanks for volunteering! Let me know if you have any questions.

**Comment by adan-ayaz-stan** [comment]
I am done with it but there's no userName functionality at the moment.
There are no popups in my application which require me to write a user name. Nor is there anything in the localStorage.


As you're gonna see this comment anyway, I might as well show you the code too.

### Frontend
The Button
![image](https://github.com/CommunityFocus/CommunityFocus/assets/97961980/e63f84e2-dabf-4dc7-8e69-f7523295929a)

Inclusion in the Room.tsx file
![image](https://github.com/CommunityFocus/CommunityFocus/assets/97961980/6348478f-94b5-4e16-8e70-9af464810ca2)

### Backend
Socket types addition
![image](https://github.com/CommunityFocus/CommunityFocus/assets/97961980/4e3bfd45-73fa-4a89-ae2e-4dcd43fa6691)

Server Side in the server.ts file.
![image](https://github.com/CommunityFocus/CommunityFocus/assets/97961980/8a269b52-ea1f-4ba8-9e3c-9900190cd6b5)

### Side question
Also, on `npm run lint` , there are 19 problems already existing ( 10 errors and 9 warnings ). Should I tamper with other contributors components to fix errors?

**Comment by nmpereira** [comment]
This looks great so far from what I see. The hard-coded string on the client side for the username is good enough for now until we add that functionality. Once you have the PR up, ill put in some comments if I have any.

One comment I have is the name of the button `WorkBreakButton` might not work for this issue since there will be a separate button for the "emit workTimer" message. I would change it to 'BreakButton'. (So that the emit workTimer button can be named to 'workButton'). 

I know this will need to be changed later, but since we want multiple issues (for learning), I chose to keep the issues small. 

Alternatively, if you want to take on https://github.com/CommunityFocus/CommunityFocus/issues/81 in addition to this one, you can call it `WorkBreakButton` since you'll be adding both functionalities. 


For the linting errors, would you be able to pull a completely separate PR for the lint errors instead of doing it on the same PR? That would help with keeping the scope of the PR to the minimum

**Comment by adan-ayaz-stan** [comment]
Alright, can I take up the issue #81 too?

Sure, I'll do separate PR for lint errors. 👍
