### ISSUE TITLE
Create frontend button to emit a 'workTimer' socket message to server

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#81]
## Description
Create a button to switch from the break timer to the work timer.

Note: No need to add styling to the button, that will be a different issue.

## How
1. Create a button with the title 'Start working'
2. The onClick would emit a socket message with the event name 'workTimer', along with the roomName, user's username (from local storage. See https://github.com/CommunityFocus/CommunityFocus/issues/32)
3. On the server, listen to the socket message with event name 'workTimer', and console log it, along with the roomName, username

Additional info:
If you want to see a similar functionality, you can see the timer button (5 min, 10 min buttons) or the pause/reset button.

## Dependencies
None

## Screenshot
![image](https://github.com/CommunityFocus/CommunityFocus/assets/45009203/ed4a5fbc-3721-49a9-9adb-fead93b39d28)

**Comment by sarafurd** [comment]
I would like to try it

**Comment by sarafurd** [comment]
I'm interested in working on it.

**Comment by nmpereira** [comment]
@adan-ayaz-stan assigning this issue to you. I'm not able to put you in as an assignee until you accept the org invite. Please go to the org page for communityfocus and you'll see and invite you can accept
