### ISSUE TITLE
Based on 'isBreakState' state, change break status text to 'WORK TIME' or 'BREAK TIME'

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#86]
## Description
Based on the state `isBreakState` on the Room component, change the text of the break/work status according to the Figma document

### Values
If `isBreak` is `true`, the timer is on break timer. The text should say 'WORK TIME'
If `isBreak` is `true`, the timer is on work timer. The text should say 'BREAK TIME'

## How
1. Create a state in the `Room` component with a boolean type and name it `isBreakState` and initialize it to false (this is also being done in https://github.com/CommunityFocus/CommunityFocus/issues/84 and https://github.com/CommunityFocus/CommunityFocus/issues/85, so might have some overlap)
2. Create a break status text on the timer that should either say 'WORK TIME' or 'BREAK TIME' (see figma for design)
3. Based on the value of this state, change the text of the break status.

## Dependencies
Depends on: https://github.com/CommunityFocus/CommunityFocus/issues/84 but can be completed without it.

## Screenshot
![image](https://github.com/CommunityFocus/CommunityFocus/assets/45009203/74026c0f-49ff-4fa6-a0d2-61cc87738133)

## Figma
https://www.figma.com/file/QBlosE3N87ufFSx3hEPJ69/CommunityFocus?type=design&node-id=201-80&t=hIxGT6FSp8tKlSnG-4

**Comment by MikeJakuszewski** [comment]
I'm interested.

**Comment by nmpereira** [comment]
> I'm interested. 

Thanks for volunteering! Assigned it to you!
