### ISSUE TITLE
Style the timestamp/controls to be centered

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#9]
## What
Create a parent component that will encase the timestamp, controls etc in the center of the screen. Make sure the timestamp/controls are centered at all breakpoints.

**Comment by nmpereira** [comment]
@kiddo7565 Do you happen to have any updates on this?

**Comment by kiddo7565** [comment]
I am still working on this. I’ve been having trouble with it. Sorry for the delay.

**Comment by nmpereira** [comment]
> I am still working on this. I’ve been having trouble with it. Sorry for the delay. @nmpereira 

Thank you for the update! If you need help, I'm free after standup or likely all day Wednesday

**Comment by kiddo7565** [comment]
@nmpereira ok I will reach out Wednesday if I don’t have it figured out by then. Thank you!
